package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"fmt"

	"github.com/emejotaw/graphql-api/graph/model"
	"github.com/emejotaw/graphql-api/internal/service"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.NewOrder) (*model.Order, error) {

	orderService := service.NewOrderService(r.db)
	order, err := orderService.Create(input)

	if err != nil {
		return nil, err
	}

	products := []*model.Product{}
	for _, p := range order.Products {

		productName := p.Name
		products = append(products, &model.Product{
			ID:       p.ID,
			Name:     &productName,
			Quantity: p.Quantity,
			Price:    p.Price,
		})
	}

	return &model.Order{
		ID:         order.ID,
		TotalPrice: order.TotalPrice,
		Products:   products,
	}, nil
}

// CraeteProduct is the resolver for the craeteProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	productService := service.NewProductService(r.db)
	product, err := productService.Create(input.Name, input.Quantity, input.Price)

	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:       product.ID,
		Name:     &product.Name,
		Quantity: product.Quantity,
		Price:    product.Price,
	}, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	productService := service.NewProductService(r.db)
	products, err := productService.FindAll()

	if err != nil {
		return nil, err
	}

	productsRespose := []*model.Product{}
	for _, product := range *products {

		name := product.Name

		productsRespose = append(productsRespose, &model.Product{
			ID:       product.ID,
			Name:     &name,
			Quantity: product.Quantity,
			Price:    product.Price,
		})
	}

	return productsRespose, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
