// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	State        string `json:"state"`
	City         string `json:"city"`
	Neighborhood string `json:"neighborhood"`
	Street       string `json:"street"`
	Number       string `json:"number"`
	ZipCode      string `json:"zipCode"`
}

type AddressInput struct {
	State        string `json:"state"`
	City         string `json:"city"`
	Neighborhood string `json:"neighborhood"`
	Street       string `json:"street"`
	Number       string `json:"number"`
	ZipCode      string `json:"zipCode"`
}

type Mutation struct {
}

type NewOrder struct {
	TotalPrice float64         `json:"totalPrice"`
	Products   []*ProductInput `json:"products"`
	Address    *AddressInput   `json:"address,omitempty"`
}

type NewProduct struct {
	Name     string  `json:"name"`
	Quantity int     `json:"quantity"`
	Price    float64 `json:"price"`
}

type ProductInput struct {
	Name     string  `json:"name"`
	Quantity int     `json:"quantity"`
	Price    float64 `json:"price"`
}

type Query struct {
}
